version: '3.1'
services:
  app:
    container_name: book_microservice
    image: book_microservice
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/books
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    container_name: db
    image: 'postgres:14-alpine'
    ports:
      - "5433:5450"
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
